config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root 'campaigns#index'
  get 'home/index'
  get 'home/about'

  concern :commentable do
    resources :comments
  end
  resources :campaigns , concern: :commentable do
    resources :do_lists
    resources :discussion_topics ,concerns: :commentable
  end

  resources :experts,:novices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/discussion_topic.rb
class DiscussionTopic < ApplicationRecord
  
  validates :title , presence: true , length: {minimum:3 } , format: { with: /[a-zA-Z]/}
  has_many :comments, as: :commentable

  belongs_to :campaign, foreign_key: "campaign_id"
  belongs_to :topic_creator , polymorphic: true

end

app/controllers/discussion_topics_controller.rb
class DiscussionTopicsController < ApplicationController
  before_action :find_campaign ,only:[:index ,:new , :create , :find_discussion_topic]
  before_action :find_discussion_topic,only:[:edit, :update,:show,:destroy]
  def index
    @discussion_topics = @campaign.discussion_topics.all
  end
  def new
   @discussion_topic = @campaign.discussion_topics.new
  end
  def show
  end
  def create
   @discussion_topic = @campaign.discussion_topics.new(discussion_topic_params)
   authorize @discussion_topic
   @discussion_topic.topic_creator_type = current_user.type
   @discussion_topic.topic_creator_id = current_user.id
   if @discussion_topic.save
      flash[:success] = "Topic Created Successfully"
      redirect_to campaign_discussion_topics_path(@campaign)
    else
      flash[:error] = "Oops Topic creation failed"
      render 'new'
    end  
  end

  def edit
   authorize @discussion_topic
  end
  def update
    authorize @discussion_topic
    if @discussion_topic.update(topic_params)
      flash[:success] = "Topic Updated Successfully"
      redirect_to discussion_topic_path(@campaign , @discussion_topic) 
    end    
      flash[:error] = "Oops Topic Updation Failed"
      render 'edit'
    end
  def destroy
    authorize @discussion_topic
    if @disucssion_topic.destroy
      flash[:success] ="Topic Deleted Successfully"
      redirect_to campaign_discussion_topics_path(@campaign)
    else
      flash[:error] = "Oops Deletion Failed"
      redirect_to campaign_discussion_topics_path(@campaign)    
    end
        
  end
  
  def find_campaign
    @campaign = Campaign.find(params[:campaign_id])      
  end
  
  def find_discussion_topic
    @campaign = Campaign.find(params[:campaign_id])
    @discussion_topic = @campaign.discussion_topics.find(params[:id]) 
  end
  private
  def discussion_topic_params
    params.require(:discussion_topic).permit(:title)
  end

end

app/helpers/discussion_topic_helper.rb
module DiscussionTopicHelper
end

app/helpers/discussion_topics_helper.rb
module DiscussionTopicsHelper
end

app/views/discussion_topics/_form.html.erb
<%= form_with model: [@campaign, @discussion_topic] do |f| %>  
  <% if @discussion_topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discussion_topic.errors.count, "error") %> prohibited this Topic from being saved:</h2>
      <ul>
        <% @discussion_topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <%end%>
  <div class="form form-group">
        <%= f.label :title, class:"col-sm-2 col-form-label"  %>

    <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control",placeholder:"Title"  %>
    </div>
  </div>
  

  <div class="form form-group">
    <div class="col-sm-10">
        <%= f.submit "Create" , class:"btn btn-info" %>      
    </div>
  </div>

<% end %>

app/views/discussion_topics/edit.html.erb
<h2> Edit Discussion Topic </h2>
<%= render 'form' %>

app/views/discussion_topics/index.html.erb
        <h3>Discussion Topics</h3>
 
    <table class="table table-striped table-bordered table-hover">
  <thead class="thead-info">
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Comments</th>
      <th>Created By</th>
      <%if current_user=="Novice"%>
      <th>Options</th>
      <%end%>
    </tr>
  </thead>
  <tbody>
  <% @discussion_topics.each_with_index do |discussion_topic, index|%>                    
    <tr>
      <th><%= index %></th>
      <td><%= link_to discussion_topic.title.capitalize, [@campaign,discussion_topic] ,id:"index_links"%></td>
      <td><%= discussion_topic.comments.count %></td>
      <td><%= discussion_topic.topic_creator.name.capitalize %></td>
      <%if discussion_topic.topic_creator.id == current_user.id%>
      <td> <%=link_to "Delete", campaign_discussion_topic_path(@campaign,discussion_topic) , method: :delete, data:{confirm:'Are you sure'} , class:'btn btn-outline-danger'%></td>
      <%end%>
    </tr>
    <% end %>
  </tbody>
  
 </table> 
 <% if policy(@discussion_topics).create? %>
    <div class="col">
        <%= link_to 'Add Topic', new_campaign_discussion_topic_path(@campaign),class:"btn btn-outline-info " ,  role:"button" %>
    </div>
  <% end %>

app/views/discussion_topics/new.html.erb
 <h2>New Topic</h2>
</div><%= render 'form' %>

app/views/discussion_topics/show.html.erb
<h3>Discussion Topic</h3>
<p class="mt-4"><strong>Title: <%= @discussion_topic.title %></strong></p>
<p><strong>Created by: <%= @discussion_topic.topic_creator.name.capitalize %></strong></p>
<% if policy(@discussion_topic).edit? && policy(@discussion_topic).destroy?  %>
<div> 
  <%= link_to "Edit", edit_campaign_discussion_topic_path(@campaign,@discussion_topic),class:'btn btn-info',id:"action_edit" %>
  <%= link_to "Delete", campaign_discussion_topic_path(@campaign,@discussion_topic),class:'btn btn-danger',id:"action_delete", method: :delete,data: { confirm: "Are you sure?" } %>
</div>
<% end %>

<div class="mt-5">
  <h5>Comments: <%= @discussion_topic.comments.count %></h5>
</div>

<%= render @discussion_topic.comments %>

<div class="row my-4 ">
  <%= render 'comments/form', locals: {commentable: @discussion_topic, type:"Discussion Topic"} %>