config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root 'campaigns#index'
  get 'home/index'
  get 'home/about'

  concern :commentable do
    resources :comments
  end
  resources :campaigns , concern: :commentable do
    resources :do_lists
    resources :discussion_topics ,concerns: :commentable
  end

  resources :experts,:novices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/novice.rb
class Novice < User
    has_many :discussion_topics, as: :topics   
end

app/controllers/novices_controller.rb
class NovicesController < ApplicationController
  before_action :find_novice, only: [:edit, :update, :show, :destroy]
  def index
    @novices = Novice.all
     authorize @novices
  end
  def show
  end

  def new
   @novice = Novice.new()
  end

  def create
    @novice = Novice.new(novice_params)
    if @novice.save
      flash[:success] = "Novice successfully created"
      redirect_to @novice
    else
      flash[:error] = "Oops Creation Failed"
      render 'new'
    end
  end

  def edit
  end
  
  def update
    if @novice.update(novice_params)
      current_user.type=="Expert"? sign_in(current_user, :bypass => true) : sign_out(current_user) 
      flash[:success] = "Novice successfully updated"
      redirect_to @novice
    else
      flash[:error] = "Oops Updataion Failed"
      render 'edit'
    end
  end

  def destroy
    @novice = Novice.find(params[:id])
    authorize @novice
    if @novice.destroy
      flash[:success] = 'Novice successfully deleted.'
      redirect_to novices_url
    else
      flash[:error] = 'Oops Deletion Failed'
      redirect_to novices_url
    end
  end
    
  def find_novice
    @novice = Novice.find(params[:id]) 
    authorize @novice       
  end
  private

  def novice_params
   current_user.type=="Novice"? params.require(:novice).permit(:name,:email,:password,:type) : params.require(:novice).permit(:name,:email,:status)
  end
end

app/helpers/novices_helper.rb
module NovicesHelper
end

app/views/novices/edit.html.erb
<div class="signup_container container">
  <div class="text-center my-2">
  <h2 class="page_heading">Edit Account</h2>
  </div>

  <%= form_with model: @novice do |f| %>
  
  <div class="form-group row mt-5">
    <%= f.label :name, class:"col-sm-2 col-form-label"  %>
    <div class="col-sm-10">
     <%= f.text_field :name, class: "form-control",placeholder:"Username"  %>
    </div>
  </div>
  
  <div class="form-group row  ">
   <%= f.label :email, class:"col-sm-2 col-form-label"  %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control",placeholder:"Email"  %>
    </div>
  </div>

  <% if current_user.type=="Novice" %>
    <div class="form-group row">
      <%= f.label "Password", class:"col-sm-2 col-form-label"  %>
    <div class="col-sm-10">
      <%= f.password_field :password, autocomplete: "new-password",class: "form-control",placeholder:"Password" %>
    </div>
  </div>

   <div class="form-group row">
      <%= f.label "Confirm Password", class:"col-sm-2 col-form-label"  %>
     <div class="col-sm-10">
      <%= f.password_field :password_confirmation, autocomplete: "new-password",class: "form-control",placeholder:"Confirm Password" %>
    </div>
  </div>
    <% else %>
    <div class="form-group row">
      <%= f.label "Status", class:"col-sm-2 col-form-label"  %>
      <div class="col-sm-10">
        <%= f.select :status, Novice.statuses.keys, {}, class:'form-control' %>
      </div>
    </div>
  <% end %>

  <div class="form-group row">
    <div class="col-sm-10">
     <%= f.submit "Update" , class:"btn btn-info" %>      
    </div>
  </div>
<% end %>
</div>

app/views/novices/index.html.erb
<div>
    <div>
        <h2 class="page_heading">Novices</h2>
    </div>
    <table class="table table-striped table-hover table-bordered index_table">
  <thead class="thead-info">
    <tr class="table_row">
      <th scope="col">Serial No</th>
      <th scope="col">Username</th>
      <th scope="col">Email</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
  <% @novices.each_with_index do |novice, index|%>                    
    <tr>
      <th scope="row"><%= index %></th>
      <td><%= link_to novice.name.capitalize, novice ,id:"index_links"%></td>
      <td><%= novice.email %></td>
      <td><%= novice.status %></td>
    </tr>
    <% end %>
  </tbody>
</table>
  <%= link_to "Back", root_path , class:'btn btn-info'%>

</div>

app/views/novices/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">  <%= @novice.name %></h1>
    <p class="lead"> Email:  <%= @novice.email %></p>
    <p class="lead"> Status: <%= @novice.status %></p>
      <%= link_to 'Edit', edit_novice_path ,class:'btn btn-info',id:"action_edit" if policy(@novice).edit? %> 
      <%= link_to 'Delete', novice_path ,class:'btn btn-info',id:"action_delete", method: :delete, data: { confirm: 'Are you sure?' } if policy(@novice).edit?%> 
  </div>
</div>