config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root 'campaigns#index'
  get 'home/index'
  get 'home/about'

  concern :commentable do
    resources :comments
  end
  resources :campaigns , concern: :commentable do
    resources :do_lists
    resources :discussion_topics ,concerns: :commentable
  end

  resources :experts,:novices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
  
    def about
        
    end
    
end
  

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light " style= "background-color: #128496;">
	<%if signed_in?%>
    <%= link_to 'Home' , root_path , class:'navbar-brand'%>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">

      </li>
             <% if user_signed_in?%>
              </li>
                  <%if user_signed_in?&& (current_user.type =='Expert')%>
                    <li class="nav-item">
                      <%= link_to :Novices, novices_path, class:'nav-link'%>
                    </li>
                    <li class="nav-item">
                      <%= link_to :Experts, experts_path,class:'nav-link'%> 
                    </li>
                    <li class="nav-item">
                      <%= link_to 'Create Campaign' , new_campaign_path , class:'nav-link'%>
                    </li> 
                  <%end%>
                   <li class="nav-item">
                   <li class="nav-item">
                     <%= link_to 'Edit Profile' ,   edit_user_registration_path , class:'nav-link'%>
                   </li>
                   <li class="nav-item" >
                     <%= link_to 'Log Out' , destroy_user_session_path ,method: :delete ,  class:'nav-link'%>
                  </li>
            
          <%else%>
       <li class="nav-item">
        <%= link_to 'Sign Up' , new_user_registration_path , class:'nav-link'%>
      </li>
       <li class="nav-item">
        <%= link_to 'Log In' ,  user_session_path , class:'nav-link'%>
      </li>
      <li class="nav-item">
      	<%= link_to 'About Us' ,  home_about_path , class:'nav-link'%>
      </li>
      
  
      <%end%>
      
    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<div class="container">
    <div class="container-fluid">
    <h2> About Page</h2>

    </div>
 
</>

app/views/home/index.html.erb
<div class ="container">
    <div class = "container-fluid">
        <h2> Home Page</h2>
    </div>
</div>
<div>

</div>