config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root 'campaigns#index'
  get 'home/index'
  get 'home/about'

  concern :commentable do
    resources :comments
  end
  resources :campaigns , concern: :commentable do
    resources :do_lists
    resources :discussion_topics ,concerns: :commentable
  end

  resources :experts,:novices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/do_list.rb
class DoList < ApplicationRecord
 validates :title , presence: true , length: {minimum:2 } , format: { with: /[a-zA-Z]/} 
 belongs_to :campaign, class_name: "Campaign", foreign_key: "campaign_id"
end

app/controllers/do_lists_controller.rb
class DoListsController < ApplicationController

  before_action :find_campaign, only: [:index, :new, :create, :find_do_list]
  before_action :find_do_list, only: [:edit, :update, :show,:destroy]
  
  def index
   @do_lists = @campaign.do_lists.all
  end
  
  def new
   @do_list =  @campaign.do_lists.new
  end

  def show
  end


  def create
   @do_list = @campaign.do_lists.new(do_list_params)
    if @do_list.save
      flash[:success] = "Goals successfully created"
      redirect_to campaign_path(@campaign)
    else
      flash[:error] = "Goal creation Failed"
      render 'new'
    end
  end

  def edit
    authorize @do_list
  end

  def update
    authorize @do_list
    if @do_list.update(do_list_params)
      flash[:success] = "Goal Successfully updated"
      redirect_to @campaign
    else
      flash[:error] = "Oops Updataion Failed"
      render 'edit'
    end
  end

  def destroy
    authorize @do_list
    if @do_list.destroy
     flash[:success] = 'Goal Successfully deleted.'
     redirect_to @campaign
    else
      flash[:error] = 'Oops Deletion Failed'
      redirect_to do_lists_url
    end
  end

  def find_campaign
    @campaign = Campaign.find(params[:campaign_id])      
  end
  
  def find_do_list
    @campaign = Campaign.find(params[:campaign_id])
    @do_list = @campaign.do_lists.find(params[:id]) 
  end

  private

  def do_list_params
    params.require(:do_list).permit(:title,:description,:completed,:campaign_id)
  end
end

app/helpers/do_lists_helper.rb
module DoListsHelper
end

app/views/do_lists/_form.html.erb
<%= form_with model: [@campaign, @do_list] do |f| %>  
  
  <div class="form-group row mt-5">
        <%= f.label :title, class:"col-sm-2 col-form-label"  %>

    <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control",placeholder:"Title"  %>
    </div>
  </div>
  <div class="form-group row mt-5">
        <%= f.label :description, class:"col-sm-2 col-form-label"  %>

    <div class="col-sm-10">
        <%= f.text_field :description, class: "form-control",placeholder:"Description"  %>
    </div>
  </div>
  
  <div class="form-group row mt-5">
        <%= f.label :completed, class: "col-sm-2 col-form-label" %>

    <div class="col-sm-10">
        <%= f.check_box :completed, class: "form-check-input mx-2" %>

    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10">
        <%= f.submit "Create" , class:"btn btn-info" %>      
    </div>
  </div>
<% end %>

app/views/do_lists/_show.html.erb
<div class="container">
  <div class="container mb-4">
    <h2> Do Lists</h2>
    <div class="row mx-4">
      <div class="col-5 offset-2 ">
        <h5>Description</h5>
      </div>
      <div class="col-3">
       <h5>Completed</h5>
      </div>
    </div>  
  </div>
  <ol>
  <% @campaign.do_lists.each do |f| %>
        <div class="container" id="do_list_content">
            <div class="row mx-1">
                <div class="col-5 offset-2">
                    <p><%= f.description %></p>
                </div>
                <div class="col-3" >
                  <%if f.completed %>
                    <p id="status_true">✔</p>
                  <% else %>
                  <p id="status_false">✖</p>         
                  <% end %>
                </div>
                <div class="col-1"  >
                  <%= link_to "Edit" ,edit_campaign_do_list_path(@campaign,f) ,class:'btn btn-info',id:"action_edit" if policy(f).edit?%>
                  <br/><br/>
                  <%= link_to "Delete", [@campaign,f],class:'btn btn-outline-danger btn-sm',id:"action_delete", method: :delete, data: {confirm: "Are you sure?"} if policy(f).destroy?%>
                  <br/><br/>
                </div>
            </div>
        </div>
<% end %>
</ol>
  <% if current_user.id==@campaign.user_id %>
   <div class="row my-2">
      <div class="col offset-2">
        <%= link_to "Add Do_list", new_campaign_do_list_path(@campaign),class:"btn btn-outline-info" ,id:"btn" , role:"button"  %>
      </div>
    </div>
  <% end %>           
</div>

app/views/do_lists/edit.html.erb
 <h2>Edit Do List</h2>
<%= render 'form' %>

app/views/do_lists/index.html.erb
<h1><%= @user.name.capitalize() %> Tasks</h1>
<h4>Description|Completed|Action</h4>
<ul>
<% @do_lists.each do |f| %>
    <li>
        <p><%= f.description %>
        <%if f.completed %>
            <p> Completed</p>
        <% else %>
         <p> Incomplete</p>
           
        <% end

        <%= link_to "Edit", edit_campaign_do_list_path(f)%>
        <%= link_to "Delete", do_list,method: :delete,data: {confirm: "Are you sure?"}%>
        </p>
    </li>
<% end %>
</ul>
<br/>

<%= link_to  "Add Task", new_campaign_do_list_path %>

app/views/do_lists/new.html.erb
 <h2>New Do List</h2>
<%= render 'form' %>